### ISSUE TITLE
Why can't I load the checkpoint?

### ISSUE THREAD

**Issue by ergo-zyh** [HACMan-2023/HACMan#1]
when I run the command:
python scripts/run.py --env hacman_bin_env --ExpID 1001 --gradient_steps 0 --initial_timesteps 0 --load_ckpt scripts/ckpts/rl_model_200000_steps.zip --eval 100 --record_video --record_from_cam agentview 

the error happens:

Traceback (most recent call last):
  File "scripts/run.py", line 71, in <module>
    model = setup_model(config, eval_env, result_folder, normalize_param=None)
  File "/home/zyh/projects/HACMan/hacman/algos/setup_model.py", line 81, in setup_model
    model = TD3.load(path=config['load_ckpt'], env=env, **td3_kwargs) # Overwrite hyperparameters of the loaded model
  File "/home/zyh/projects/HACMan/stable-baselines3/stable_baselines3/common/base_class.py", line 714, in load
    data, params, pytorch_variables = load_from_zip_file(
  File "/home/zyh/projects/HACMan/stable-baselines3/stable_baselines3/common/save_util.py", line 419, in load_from_zip_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/zyh/projects/HACMan/stable-baselines3/stable_baselines3/common/save_util.py", line 164, in json_to_data
    deserialized_object = cloudpickle.loads(base64_object)
ModuleNotFoundError: No module named 'hacman.feature_extractors'

**Comment by JiangBowen0008** [comment]
Thanks for raising the issue! 

I have just tested it and was able to reproduce the error you saw. This apparently is due to the checkpoint trained with an older codebase. We will retrain and upload the new checkpoints compatible with the latest code.

Meanwhile, please feel free to run the training script which should also generate checkpoint with performance similar to the ones we were using.

**Comment by JiangBowen0008** [comment]
Checkpoints updated and re-uploaded.
